AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
