language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby
  - rbx-3
  - truffleruby
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler:1.16.1
matrix:
  allow_failures:
      - rvm: rbx-3
      - rvm: jruby
      - rvm: truffleruby

