sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - jruby
  - rbx-3
  - ruby-head
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
      - rvm: rbx-3
