name: Push gem

on:
  pull_request:
    branches: ["main"]

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment: Release

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - run: ./zig/download.sh && ./zig/zig run scripts/tp_test.zig
